Issue  #10: support concatenation in yaml connectors for attribute mapping
sentrysoftware/metricshub pull request #15
Opened 2024-01-26 16:19 UTC by kawtarBK9

* Adjusted the concatenation in the MappingProcessor to invoke the concatenateColumnsValue method.
* Implement relevant test cases to reflect the corrected behavior.

2024-01-26 19:03 UTC, NassimBtk requested changes
Please update the integration test in the hardware module.
In `SuperConnectorCommon-header.yaml` define a new attribute for the `enclosure` monitor:
```yaml
attributes:
  vendor_and_model: $4 $5
   # other attributes...
```
Then in `expected.json`, add this new attribute (`vendor_and_model`) to the enclosure's expected attributes:
```json
    "attributes" : {
      "__display_id" : "000297800620 1",
      "vendor" : "EMC",
      "name" : "Enclosure: 000297800620 1 (EMC VMAX250F)",
      "connector_id" : "SuperConnectorOS",
      "model" : "VMAX250F",
      "id" : "2",
      "type" : "Storage",
      "info" : "Serial number : 297800620",
      "vendor_and_model" : "EMC VMAX250F"
    }
```

2024-01-28 12:41 UTC, NassimBtk requested changes
Some points to consider:

1. The regex is wrong and should be created as a constant. Here is the right pattern:
    ```java
      	private static final Pattern COLUMN_REFERENCE_PATTERN = Pattern.compile("\\$(\\d+)");
     ```
3. It is not required to use a _thread-safe_ object but even the entire object stringbuffer `resultBuffer` is not required in fact, to simplify and improve the code quality, we should invoke the [Matcher#replaceAll​(Function<MatchResult,​String> replacer)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Matcher.html#replaceAll(java.util.function.Function)) introduced since Java 9.
4. The current implementation will fail if the column value contains a value such as `$N` where N is an number. Example: $1.
5. Javadoc should be completed and added even for private methods.
6. Integration tests should be added to SuperConnector IT.
7. Log messages need to be enhanced to report more context about failures.

Please consider the following implementation:

```java
	/**
	 * Creates a matcher that will match the given value against the column
	 * reference pattern.
	 *
	 * @param value The string value on which the regular expression pattern will be applied.
	 * @return A Matcher object that can be used to perform matching operations on the input string.
	 */
	private Matcher getColumnReferenceMatcher(String value) {
		return COLUMN_REFERENCE_PATTERN.matcher(value);
	}

	/**
	 * Replaces in the given value each column reference (E.g. $1) with the corresponding column value from the current row.
	 *
	 * @param value The input string containing placeholder notations.
	 * @param key   A key of the attribute.
	 * @return The modified string after replacing column references with actual values.
	 */
	protected String replaceColumnReferences(final String value, final String key) {
		return getColumnReferenceMatcher(value).replaceAll(match -> getColumnValue(match, key));
	}

	/**
	 * Retrieves the value of the column referenced in the match and replaces the match in the input string.
	 *
	 * @param match The MatchResult containing the column reference.
	 * @param key   A key of the attribute used for logging.
	 * @return The column value if available, or the original match if the column is not found.
	 */
	private String getColumnValue(final MatchResult match, final String key) {
		final int columnIndex = Integer.parseInt(match.group(1)) - 1;
		if (columnIndex >= 0 && columnIndex < row.size()) {
			final String columnValue =  row.get(columnIndex);
			if (columnValue != null) {
				return Matcher.quoteReplacement(columnValue);
			} else {
                               // TODO add context.
				log.warn(...);
			}
		} else {
                        // TODO add context. 
			log.warn(...);
		}

		return Matcher.quoteReplacement(match.group());
	}
```

2024-01-28 12:41 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessorTest.java
> +		assertEquals(expectedResult7, mappingProcessor.concatenateColumnsValue(invalidPlaceholder, key7));
When the placeholder is beyond the row size we shouldn't force empty.

2024-01-30 05:05 UTC, NassimBtk requested changes

2024-01-30 16:12 UTC, TNohaic requested changes
Just a JavaDoc to update and it's good to go

2024-01-30 16:12 UTC, TNohaic commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
> +	 * Checks whether the input string represents a column concatenation
JavaDoc still needs to be updated

2024-01-30 16:12 UTC, TNohaic commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
> +	 * @param value
JavaDoc still needs to be updated

2024-01-30 16:12 UTC, TNohaic commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/utils/MappingProcessor.java
> +	 * @return true or false
JavaDoc still needs to be updated

2024-01-30 16:38 UTC, TNohaic approved these changes

2024-01-30 17:17 UTC, NassimBtk approved these changes

2024-01-30 17:17 UTC, merged