Issue #218: Add a hostname to be used as a class member in all the extensions
sentrysoftware/metricshub pull request #292
Opened 2024-06-28 14:52 UTC by CherfaElyes

* Added a getHostname() method to the TelemetryManager, which allows to return the hostname from a specific IConfiguration classes list, otherwise from the TelemetryManager.
* Added a hostname for each IConfiguration.
* Refactored all the Extensions to use the new getHostname() method.
* Refactored unit tests to make them run again.
* Tested all the protocols using MetricsHub engine.
* Documented the changes.

2024-06-28 15:48 UTC, NassimBtk requested changes

2024-06-28 15:48 UTC, NassimBtk commented on metricshub-doc/src/site/markdown/configuration/configure-agent.md
> +2. A hostname on each metric in Prometheus.
`2. The hostname of each OpenTelemetry metric attached to the host resource.`

2024-06-28 15:48 UTC, NassimBtk commented on metricshub-doc/src/site/markdown/configuration/configure-agent.md
> +If the `hostname` parameter is specified in the protocol configuration, it overrides the `host.name` attribute for client requests. The `host.name` will be used only as a metric hostname in Prometheu
If the `hostname` parameter is specified in the protocol configuration, it overrides the `host.name` attribute for client requests. The `host.name` will be used only as a metric attribute.

2024-06-28 15:48 UTC, NassimBtk commented on metricshub-snmp-extension-common/src/test/java/org/sentrysoftware/metricshub/extension/snmp/source/SnmpGetSourceProcessorTest.java
> +	// Utility method to create a telemetryManager
Can we fix the javadoc here please.

2024-06-28 15:48 UTC, NassimBtk commented on metricshub-snmp-extension-common/src/test/java/org/sentrysoftware/metricshub/extension/snmp/source/SnmpTableSourceProcessorTest.java
> +	private TelemetryManager createTelemetryManagerWithHostConfiguration() {
Java doc is better ;)

2024-06-28 15:48 UTC, NassimBtk commented on metricshub-win-extension-common/src/main/java/org/sentrysoftware/metricshub/extension/win/detection/WmiCriterionProcessor.java
> +						"Hostname {} - Does not respond to {} requests. {}: {}\nCancelling namespace detection.",
Thank you 🤔

2024-06-28 15:57 UTC, CherfaElyes commented on metricshub-win-extension-common/src/main/java/org/sentrysoftware/metricshub/extension/win/detection/WmiCriterionProcessor.java
> +						"Hostname {} - Does not respond to {} requests. {}: {}\nCancelling namespace detection.",
My pleasure

2024-07-01 08:33 UTC, NassimBtk approved these changes

2024-07-01 08:42 UTC, merged