Issue #18: Ssh Protocol Check Metric
sentrysoftware/metricshub pull request #34
Opened 2024-02-13 15:04 UTC by CherfaElyes

* Developped SSH protocol health check
* Created a test case for SSH protocol health check
* Tested SSH protocol health check on metricshub with the agent

2024-02-13 15:14 UTC, NassimBtk requested changes
Missing OsCommand remote and local executions  management.

2024-02-15 18:37 UTC, NassimBtk requested changes

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +					.sequential(false)
sequential is not required in all the telemetry managers.

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +		// Create a telemetry manager using an SNMP HostConfiguration.
`// Create a telemetry manager using an SSH HostConfiguration.`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +			// Start the SNMP Health Check strategy
`// Start the SSH Health Check strategy`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +		// Create a telemetry manager using an SNMP HostConfiguration.
`// Create a telemetry manager using an SSH HostConfiguration.`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +			// Start the SNMP Health Check strategy
`// Start the SSH Health Check strategy`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +			// Start the SNMP Health Check strategy
`// Start the SSH Health Check strategy`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +		// Create a telemetry manager using an SNMP HostConfiguration.
`// Create a telemetry manager using an SSH HostConfiguration.`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +			// Start the SNMP Health Check strategy
`// Start the SSH Health Check strategy`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +			// Start the SNMP Health Check strategy
`// Start the SSH Health Check strategy`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +			// Start the SNMP Health Check strategy
`// Start the SSH Health Check strategy`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +		// Create a telemetry manager using an SNMP HostConfiguration.
`// Create a telemetry manager using an SSH HostConfiguration.`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +		// Start the SNMP Health Check strategy
`// Start the SSH Health Check strategy`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +		// Create a telemetry manager using an SNMP HostConfiguration.
`// Create a telemetry manager without configuration.`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +		// Start the SNMP Health Check strategy
`// Start the SSH Health Check strategy`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategyTest.java
> +			// Start the SNMP Health Check strategy
`// Start the SSH Health Check strategy`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/DetectionStrategy.java
> +	 * @param criteria Connector detection criteria list
Javadoc is wrong.
`@param sourceTypes Connector source types`

2024-02-15 18:37 UTC, NassimBtk commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/detection/DetectionStrategy.java
> +	void verifySshSources(final Set<Class<? extends Source>> sources) {
`void verifySshSources(final Set<Class<? extends Source>> sourceTypes) {`

2024-02-15 22:58 UTC, CherfaElyes commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java
> +	 * @param sshResult         The results that will be used to create protocol health check metric
There is a conflict between this variable name "previousSshStatus" and the one you chose in the method signature which was "osCommandStatus". I'll be using "previousSshStatus".

2024-02-19 09:31 UTC, NassimBtk commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java
> +	private Double remoteSshTest(String hostname, Double sshResult, SshConfiguration sshConfiguration) {
private Double remoteSshTest(String hostname, Double previousSshStatus, SshConfiguration sshConfiguration) {

2024-02-19 09:31 UTC, NassimBtk commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/collect/ProtocolHealthCheckStrategy.java
> +	 * @param sshResult         The results that will be used to create protocol health check metric
The right name is the one provided in the javadoc.

2024-02-19 09:33 UTC, NassimBtk requested changes
Additional changes are required.

2024-02-19 17:28 UTC, NassimBtk approved these changes

2024-02-19 17:29 UTC, merged