Issue #427: Add statutus information to connector monitor
sentrysoftware/metricshub pull request #431
Opened 2024-09-27 14:38 UTC by MedMaalej

- Add buildStatusInformation in AbstractStrategy
- Set StatusInformation in the legacyTextParams attribute (map) of the connector monitor
- Update unit tests

2024-09-27 14:42 UTC, MedMaalej commented
This feature was tested locally using the connector `WinStorageSpaces`. Here is a metricshub log showing the `StatusInformation ` field in legacyTextParams of the connector monitor.

<img width="704" alt="successful" src="https://github.com/user-attachments/assets/e0b76696-96e5-419c-bb1b-2a9504091087">

2024-09-27 16:01 UTC, NassimBtk requested changes

2024-09-27 16:01 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
> +			"SnmpGetNextCriterion(super=SnmpCriterion(super=Criterion(type=snmpGetNext, forceSerialization=false), oid=1.3.6.1.4.1.795.10.1.1.3.1.1, expectedResult=null))\n" +
Can you please @MedMaalej update the toString() method on `DeviceTypeCriterion`, `HttpCriterion`, `ProcessCriterion`, `ProductRequirementsCriterion` and `SnmpCriterion`. Please use the same pattern as on `CommandLineCriterion`. Thanks.

2024-09-30 12:58 UTC, NassimBtk requested changes

2024-09-30 13:12 UTC, NassimBtk requested changes

2024-09-30 13:12 UTC, NassimBtk commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
> +				return String.format(
Each extension provides the messages in a specific format. We need to normalize all the messages. It is a huge work but we should do that to get normalized messages for BMC or even for OTEL logs.

2024-09-30 15:45 UTC, NassimBtk commented
Also @MedMaalej how is the `StatusInformation` parameter displayed using the CLI?

2024-10-08 10:11 UTC, NassimBtk requested changes

2024-10-08 10:11 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java
> +@Disabled
Removed disabled.

2024-10-08 10:11 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/discovery/DiscoveryStrategyTest.java
> +@Disabled
Remove disabled.

2024-10-08 10:11 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
> +@Disabled
Remove disabled.

2024-10-08 10:32 UTC, NassimBtk approved these changes

2024-10-08 10:32 UTC, merged