Issue #480: Fix IpmitoolCommand
sentrysoftware/metricshub pull request #483
Opened 2024-11-13 15:16 UTC by MedMaalej

* Update buildIpmiCommand
* Update processUnixIpmiDetection
* Update unit tests

2024-11-14 14:28 UTC, MedMaalej commented
Tested with host "babbage" using the connector "IpmiTool".

The error is fixed, 3 monitors were discovered without any ipmi command error ✔️

![Capture d'écran 2024-11-13 161855](https://github.com/user-attachments/assets/a941faad-d96a-4b33-8abf-8e372755de8e)
![Capture d'écran 2024-11-13 161822](https://github.com/user-attachments/assets/7cb0f0be-dc07-4d44-9321-22b93c1f37b6)

2024-11-14 14:43 UTC, NassimBtk commented
We should discover more than 3 monitors using Unix ipmitool

2024-11-14 14:43 UTC, NassimBtk commented
Can you please @MedMaalej check why we are not discovering the hardware devices?

2024-11-15 09:48 UTC, NassimBtk requested changes

2024-11-15 09:48 UTC, NassimBtk commented on metricshub-oscommand-extension/src/main/java/org/sentrysoftware/metricshub/extension/oscommand/ipmi/UnixIpmiCriterionProcessor.java
Probably we have an issue with `IpmiHelper.ipmiTranslateFromIpmitool(fruResult, sensorResult)` and the IpmiTool connector's awk script which produces `OK`, `WARN`, `ALARM` instead of `ok`, `degraded`, `failed`.

2024-11-18 16:47 UTC, NassimBtk approved these changes

2024-11-18 16:47 UTC, merged