Issue #465: Add job duration metric for monitor jobs
sentrysoftware/metricshub pull request #507
Opened 2024-12-02 13:42 UTC by MedMaalej

* Add a method that sets the duration metric in AbstractStrategy
* Call the created method
* Update unit tests
* Initialize and refresh metrics after discovery job in MonitoringTask

2024-12-02 13:47 UTC, MedMaalej commented
I tested this ticket using windows connectors locally.

The job duration metric was displayed correctly in MetricsHub logs.

Here are the screenshots of the Grafana Dashboard that uses MetricsHub metrics:
![Capture d'écran 2024-12-02 134638](https://github.com/user-attachments/assets/060f21ca-52da-4a68-9297-8082df983c12)

![Capture d'écran 2024-12-02 134657](https://github.com/user-attachments/assets/457856dc-d4e5-4b73-8d96-def9baad70f1)

![Capture d'écran 2024-12-02 134706](https://github.com/user-attachments/assets/b6484407-3680-44e8-a36d-ff138a6962e5)

2024-12-02 13:58 UTC, NassimBtk requested changes
Updates requires on junit tests.

2024-12-02 13:58 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/AfterAllStrategyTest.java
> +					"metricshub.job.duration{job.type=\"afterAll\"," + " monitor.type=\"none\", connector_id=\"afterAllSource\"}"
It is not required to concatenate strings.

2024-12-02 13:58 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java
> +					"metricshub.job.duration{job.type=\"simple\"," +
String concat is not required.

2024-12-02 13:58 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/simple/SimpleStrategyTest.java
> +					"metricshub.job.duration{job.type=\"simple\"," +
Same as previous comment about string concat.

2024-12-02 13:58 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/AfterAllStrategyTest.java
> +					"metricshub.job.duration{job.type=\"collect\"," +
Same as previous comments about string concatenation.

2024-12-02 13:58 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/BeforeAllStrategyTest.java
> +					"metricshub.job.duration{job.type=\"collect\"," +
Update please.

2024-12-02 13:58 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/BeforeAllStrategyTest.java
> +					"metricshub.job.duration{job.type=\"beforeAll\"," +
Update please.

2024-12-02 13:58 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/surrounding/BeforeAllStrategyTest.java
> +					"metricshub.job.duration{job.type=\"collect\"," +
Update please.

2024-12-02 13:58 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
> +					"metricshub.job.duration{job.type=\"collect\"," +
It not required to concatenate strings.

2024-12-02 13:58 UTC, NassimBtk commented on metricshub-engine/src/test/java/org/sentrysoftware/metricshub/engine/strategy/collect/CollectStrategyTest.java
> +					"metricshub.job.duration{job.type=\"collect\"," +
do not concatenate strings.

2024-12-02 14:00 UTC, NassimBtk requested changes

2024-12-02 14:00 UTC, NassimBtk commented on metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/service/task/MonitoringTask.java
> +			// Initialize metric observers
This requires an additional comment to explain why we are doing this here, please.

2024-12-02 14:00 UTC, NassimBtk commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
> +			(double) (endTime - startTime) / 1000, // Job duration in seconds
```suggestion
			(endTime - startTime) / 1000.0, // Job duration in seconds
```

2024-12-04 08:50 UTC, NassimBtk approved these changes

2024-12-04 08:50 UTC, merged