Issue #424: Add CLI options for specific query execution - SNMP
sentrysoftware/metricshub pull request #508
Opened 2024-12-03 00:41 UTC by CherfaElyes

* Added IQuery interface to handle protocols queries.
* Developed SnmpCli executable which enables to execute SNMP get, getNext & walk commands through CLI.
* Tested the generated SNMP.exe with different commands.

# Tests
## SNMP Get
![image](https://github.com/user-attachments/assets/c307b1a4-a1af-4602-8598-d293e638ddeb)

 ## SNMP GetNext
![image](https://github.com/user-attachments/assets/dd0dc843-1504-450b-9252-f8c0abcb0137)

## SNMP Walk
![image](https://github.com/user-attachments/assets/e30ca2cc-a3bc-4ef0-9573-cf5592a6e3a6)

2024-12-03 16:36 UTC, NassimBtk requested changes
Small updates and we are good to go.

2024-12-03 16:36 UTC, NassimBtk commented on metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/snmp/SnmpCli.java
> +public class SnmpCli implements IQuery, Callable<Integer> {
Add Javadoc please.

2024-12-03 16:36 UTC, NassimBtk commented on metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/snmp/SnmpCli.java
> +	public static void main(String[] args) {
Javadoc.

2024-12-03 16:36 UTC, NassimBtk commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/common/IQuery.java
> +import com.fasterxml.jackson.databind.JsonNode;
Move this import after the MetricsHub Engine bloc.

2024-12-03 16:36 UTC, NassimBtk commented on metricshub-snmp-extension-common/src/main/java/org/sentrysoftware/metricshub/extension/snmp/AbstractSnmpRequestExecutor.java
> +		 *
Add comment.

2024-12-03 16:36 UTC, NassimBtk commented on metricshub-snmp-extension/src/main/java/org/sentrysoftware/metricshub/extension/snmp/SnmpExtension.java
> +			printWriter.print("\n\u001B[34m");
Remove the color please.

2024-12-04 12:33 UTC, CherfaElyes commented on metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/snmp/SnmpCli.java
> +	@ArgGroup(exclusive = false, heading = "%n@|bold,underline SNMP Options|@:%n")
Based on what I've noticed on MetricsHubCliService, order is not included in all ArgGroups 🤷‍♂️

2024-12-04 12:51 UTC, CherfaElyes commented on metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/snmp/SnmpCli.java
> +		if (snmpConfigCli == null) {
It's simple especially on SNMP, is it the same thing on the other protocols?

2024-12-04 13:18 UTC, NassimBtk commented on metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/snmp/SnmpCli.java
> +		if (snmpConfigCli == null) {
Each CLI is protocol-specific, so other protocols might not share the same behavior. For instance, in HTTP, you could imagine a command like `http.exe https://domain.net/systems` that execute an HTTP GET on the specified url.

2024-12-27 09:07 UTC, closed without merging