Issue #518: Enable job duration metric reporting through MetricsHub configuration
sentrysoftware/metricshub pull request #522
Opened 2024-12-16 13:50 UTC by MedMaalej

* Transfer the new flag to HostConfiguration in Agent configuration helper
    * Add the flag to HostConfiguration
    * Update agent and engine tests
    * Refactor the method setJobDurationMetricInHostMonitor to include the new flag value check

2024-12-16 14:07 UTC, MedMaalej commented
I tested the following test cases:
- No configuration at all
- Only global configuration is set
- Global configuration is set then overridden
- Only resource group configuration is set
- Only resource configuration is set

# Test cases
## No configuration at all
### Configuration:
 
 
```
# No global configuration
resourceGroups:
  # Resource Group identifier
  sentry-paris:
    # Adds additional static attributes to all the resources in the group.
    attributes:
      site: Sentry-Paris
   # Simple resource configuration
    resources:
      localhost:
              #loggerLevel: debug
        attributes:
          host.name: localhost
          host.type: windows
        protocols:
          wmi:
            timeout: 120s
```

### Result in Prometheus:
<img width="935" alt="NoConfig" src="https://github.com/user-attachments/assets/c28be415-2eb4-4fb3-bf4d-9ce69fa74d2f" />

## Only global configuration is set to false

### Configuration
```
enableSelfMonitoring: false
resourceGroups:
    # Resource Group identifier
  sentry-paris:
    # Adds additional static attributes to all the resources in the group.
    attributes:
      site: Sentry-Paris
# Simple resource configuration
    resources:
      localhost:
              #loggerLevel: debug
        attributes:
          host.name: localhost
          host.type: windows
        protocols:
          wmi:
            timeout: 120s
```
### Result in Prometheus
<img width="955" alt="onlyGlobalFalse" src="https://github.com/user-attachments/assets/16fbdc0f-2992-4be7-8a7a-83c0df086c3c" />

## Only global configuration is set to true
### Configuration
```
enableSelfMonitoring: true
resourceGroups:
    # Resource Group identifier
  sentry-paris:
    # Adds additional static attributes to all the resources in the group.
    attributes:
      site: Sentry-Paris
# Simple resource configuration
    resources:
      localhost:
              #loggerLevel: debug
        attributes:
          host.name: localhost
          host.type: windows
        protocols:
          wmi:
            timeout: 120s
```
### Result in Prometheus
<img width="937" alt="onlyGlobalTrue" src="https://github.com/user-attachments/assets/f9a322d6-6407-4ad4-84b3-55254ac25515" />

## Global configuration is set then overridden
## Configuration
```
enableSelfMonitoring: false
resourceGroups:
    # Resource Group identifier
  sentry-paris:
    enableSelfMonitoring: true
    # Adds additional static attributes to all the resources in the group.
    attributes:
      site: Sentry-Paris
# Simple resource configuration
    resources:
      localhost:
        enableSelfMonitoring: false
              #loggerLevel: debug
        attributes:
          host.name: localhost
          host.type: windows
        protocols:
          wmi:
            timeout: 120s
```
### Result in Prometheus
<img width="953" alt="overrides" src="https://github.com/user-attachments/assets/f8118306-2629-431b-943b-ea6ec57e351b" />

## Only resource group configuration is set
### Configuration
```
resourceGroups:
    # Resource Group identifier
  sentry-paris:
    enableSelfMonitoring: false
    # Adds additional static attributes to all the resources in the group.
    attributes:
      site: Sentry-Paris
# Simple resource configuration
    resources:
      localhost:
              #loggerLevel: debug
        attributes:
          host.name: localhost
          host.type: windows
        protocols:
          wmi:
            timeout: 120s
```
### Result in Prometheus
<img width="953" alt="onlyResourceGroup" src="https://github.com/user-attachments/assets/e386002c-8e61-4a21-9ee6-55daa9636b55" />

## Only resource configuration is set
### Configuration
```
resourceGroups:
    # Resource Group identifier
  sentry-paris:
    # Adds additional static attributes to all the resources in the group.
    attributes:
      site: Sentry-Paris
# Simple resource configuration
    resources:
      localhost:
        enableSelfMonitoring: false
              #loggerLevel: debug
        attributes:
          host.name: localhost
          host.type: windows
        protocols:
          wmi:
            timeout: 120s
```
### Result in Prometheus
<img width="947" alt="onlyResource" src="https://github.com/user-attachments/assets/2872fb71-4a92-47f9-a1a8-74d8888954a2" />

## Grafana tests

In Grafana, when the flag enableSelfMonitoring is set to true or not configured, we have the following result:
<img width="934" alt="grafanaJobDuration" src="https://github.com/user-attachments/assets/c23d7a96-aa03-4978-badf-b6f0ee002919" />

However, when the flag enableSelfMonitoring is set to false, the job duration metrics are not displayed:
![GrafanaNoJobDuration](https://github.com/user-attachments/assets/5bdbbd9e-006a-4e37-8295-bd12d785dfbe)

2024-12-16 17:44 UTC, NassimBtk requested changes

2024-12-18 13:11 UTC, NassimBtk requested changes
One last change and we are good to go.

2024-12-18 13:11 UTC, NassimBtk commented on metricshub-agent/src/main/java/org/sentrysoftware/metricshub/agent/config/AgentConfig.java
> +	private boolean enableSelfMonitoring = Boolean.TRUE;
`private boolean enableSelfMonitoring = true;`

2024-12-18 13:31 UTC, NassimBtk approved these changes

2024-12-18 14:34 UTC, merged