Issue #525: Add job duration metrics to connectors
sentrysoftware/metricshub pull request #528
Opened 2024-12-27 14:46 UTC by MedMaalej

* Compute job duration in validateConnectorDetectionCriteria
    * Remove monitorType('none') from surrounding strategy job duration metric
    * Add documentation for enableSelfMonitoring in configure-monitoring.md
    * Add unit tests

2024-12-27 15:01 UTC, MedMaalej commented
I tested this ticket on the host ` emc-vnxe`.

### Before the new development

We were not able to have job duration metrics in the connector monitors.

![beforeChange](https://github.com/user-attachments/assets/57346151-a3d7-42be-a73f-0154672caa9d)

The logs of metricshub reported that **53 monitors** were discovered.

![beforeLog](https://github.com/user-attachments/assets/f8df0278-fe79-4caf-bd28-b078cf07f507)

### After the new development

We are able to have job duration metrics in the connector monitors.

![newFeature](https://github.com/user-attachments/assets/b001c547-70cd-4303-85c1-5f70f30f4e19)

![new_feature2](https://github.com/user-attachments/assets/f1d53671-6c41-4808-8837-62d38612fdb7)

The logs of metricshub also reported that **53 monitors** were discovered :heavy_check_mark:

![afterLog](https://github.com/user-attachments/assets/076c0b18-6a7a-48f3-b03b-99bdaee28cda)

### Non regression test

The other job duration metrics were not impacted and they still show up correctly.

![Non-regression1](https://github.com/user-attachments/assets/8ca14789-45f0-40eb-b642-8e0b69a773a5)

### Grafana test

The monitor type **connector** is now displayed in the drop-down list values

![Capture d'écran 2024-12-27 155755](https://github.com/user-attachments/assets/6b11c873-81e0-470f-a048-f5dd58c511c6)
![Capture d'écran 2024-12-27 155744](https://github.com/user-attachments/assets/d7f4e42e-54b2-4361-9f10-d35bd6a9d4b7)

### Surrounding strategy job duration metric test

Metricshub logs display the job duration metric of the beforeAll and afterAll strategies without a monitor type

```
"metricshub.job.duration{job.type=\"beforeAll\", connector_id=\"EMCuemcli\"}" : {
        "name" : "metricshub.job.duration{job.type=\"beforeAll\", connector_id=\"EMCuemcli\"}",
        "collectTime" : 1735310474120,
        "previousCollectTime" : 1735310400078,
        "attributes" : {
          "job.type" : "beforeAll",
          "connector_id" : "EMCuemcli"
        },
        "resetMetricTime" : false,
        "value" : 0.955,
        "previousValue" : 0.945,
        "type" : "NumberMetric",
        "updated" : true
} 

```

2024-12-30 09:16 UTC, iguitton commented
@MedMaalej , @NassimBtk : I suggest documenting the self-monitoring feature in a dedicated markdown file that will be placed under a Troubleshooting section (like we did for the hws doc: https://www.aws-dev.sentrysoftware.com/docs/hws-doc/latest/troubleshooting/self-monitoring.html). If you both agree, I will move forward and make the required changes.

2025-01-02 16:32 UTC, NassimBtk commented
> @MedMaalej , @NassimBtk : I suggest documenting the self-monitoring feature in a dedicated markdown file that will be placed under a Troubleshooting section (like we did for the hws doc: https://www.aws-dev.sentrysoftware.com/docs/hws-doc/latest/troubleshooting/self-monitoring.html). If you both agree, I will move forward and make the required changes. I can perform this task through #529

Yes, I agree with you @iguitton showing `self-monitoring` in the Troubleshooting section is an excellent idea. We could showcase a real use case there and include graphs to highlight jobs that run slowly and might affect collection performance. However, I would still keep the instructions for disabling and re-enabling the option in configure-monitoring.md, since each variable in `metricshub.yaml` is documented there. We shouldn’t add too much detail in this section; instead, we can link from self-monitoring.md to `configure-monitoring.md#self-monitoring`. What do you think, @iguitton?

2025-01-02 16:33 UTC, NassimBtk requested changes
Review done.

2025-01-02 16:33 UTC, NassimBtk commented on metricshub-engine/src/main/java/org/sentrysoftware/metricshub/engine/strategy/AbstractStrategy.java
> +	protected void setJobDurationMetricInHostMonitorWithoutMonitorType(
The method names (`setJobDurationMetricInHostMonitorWithoutMonitorType` and `setJobDurationMetricInHostMonitorWithMonitorType`) are overly verbose. `setJobDurationMetric` is already sufficiently descriptive, especially when supplemented by clear Javadoc that explains the method's behavior.

2025-01-03 08:32 UTC, iguitton commented
> > @MedMaalej , @NassimBtk : I suggest documenting the self-monitoring feature in a dedicated markdown file that will be placed under a Troubleshooting section (like we did for the hws doc: https://www.aws-dev.sentrysoftware.com/docs/hws-doc/latest/troubleshooting/self-monitoring.html). If you both agree, I will move forward and make the required changes. I can perform this task through #529
> 
> Yes, I agree with you @iguitton showing `self-monitoring` in the Troubleshooting section is an excellent idea. We could showcase a real use case there and include graphs to highlight jobs that run slowly and might affect collection performance. However, I would still keep the instructions for disabling and re-enabling the option in configure-monitoring.md, since each variable in `metricshub.yaml` is documented there. We shouldn’t add too much detail in this section; instead, we can link from self-monitoring.md to `configure-monitoring.md#self-monitoring`. What do you think, @iguitton?

Sounds like a good idea to me @NassimBtk and @MedMaalej

2025-01-03 14:42 UTC, iguitton commented
@MedMaalej , @NassimBtk : this new feature will be documented through https://github.com/sentrysoftware/metricshub/issues/533. Feel free to merge the PR when dev is ready.

2025-01-03 15:55 UTC, NassimBtk approved these changes

2025-01-03 15:56 UTC, merged