Issue #74: No Such Element Exception raised during windows collect
sentrysoftware/metricshub pull request #81
Opened 2024-03-05 15:05 UTC by CherfaElyes

* Fixed the NoSuchElementException
* Removed duplicated connector detection criteria validation

2024-03-05 15:54 UTC, CherfaElyes commented
![image](https://github.com/sentrysoftware/metricshub/assets/152391385/1dee2d22-57d6-4c9d-b889-3564f7d637d6)

2024-03-05 18:14 UTC, NassimBtk requested changes
Minor changes and we are good to go.

2024-03-05 18:14 UTC, NassimBtk commented on metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterService.java
> +			final Map<String, AbstractMetric> metrics = monitor.getMetrics();
`monitor.getMetrics()` is called several times, create a variable please.

2024-03-05 18:14 UTC, NassimBtk commented on metricshub-agent/src/main/java/org/sentrysoftware/metricshub/cli/service/PrettyPrinterService.java
> +		if (monitor.getMetrics() != null && !monitor.getMetrics().isEmpty()) {
To verify metrics, I would use the following approach:
```java
		// Get the metrics
		final Map<String, AbstractMetric> metrics = monitor.getMetrics();

		if (metrics == null || metrics.isEmpty()) {
			return;
		}
```

2024-03-06 10:32 UTC, NassimBtk approved these changes

2024-03-06 10:32 UTC, merged