Issue 89: Reviewed configure-agent.md
sentrysoftware/metricshub pull request #91
Opened 2024-03-07 13:29 UTC by iguitton

* reviewed the entire file
* restructured the file
* rephrased sections for better clarity
* updated the quick start page to be consistent with the updated version of configure-agent.md

2024-03-07 13:30 UTC, iguitton commented
@NassimBtk , this branch should be merged after https://github.com/sentrysoftware/metricshub/pull/90

2024-03-07 17:12 UTC, NassimBtk requested changes
Minor updates, conflict resolution and we should be good.

2024-03-07 17:12 UTC, NassimBtk commented on metricshub-doc/src/site/markdown/configuration/configure-agent.md
> +where `<my host>` should be replaced with the hostname or IP address of the server where the OTLP receiver is installed.
Small typo, we should reference `<my-host>`

2024-03-08 09:25 UTC, iguitton commented
Thanks @NassimBtk for your feedback. I took your comments into account. Please re-review :)

2024-03-08 10:06 UTC, NassimBtk approved these changes

2024-03-08 10:06 UTC, merged